### ISSUE TITLE
Policy Engine identifier for the PolicyReport

### ISSUE THREAD

**Issue by anusha94** [kubernetes-sigs/wg-policy-prototypes#116]
Currently, we have the [source](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/bb2ec18a02da94e9a860feeaecc9115484278a23/policy-report/pkg/api/wgpolicyk8s.io/v1beta1/policyreport_types.go#L71-L73) field in the `PolicyReportResult` struct. This is used to specify the policy engine managing this report.

We do not anticipate a case where different policy engines will govern different policies, thereby creating policy reports from engines A and B. Move the source field to the top level [PolicyReport](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/bb2ec18a02da94e9a860feeaecc9115484278a23/policy-report/pkg/api/wgpolicyk8s.io/v1beta1/policyreport_types.go#L132) schema

**Comment by gparvin** [comment]
We actually have 2 different engines that use this field as you describe.
Our Insights client creates results with this source:
`source: insights`
and our governance engine creates results in the same PolicyReport with this source:
`source: grc`

**Comment by anusha94** [comment]
Per this [slack discussion](https://kubernetes.slack.com/archives/C906A4GAF/p1678141530743389?thread_ts=1677862799.172649&cid=C906A4GAF), I will proceed with adding the `source` field at the top level, while keeping the existing field as is. Both these fields will be optional.
