### ISSUE TITLE
Add a Configuration field to PolicyReport

### ISSUE THREAD

**Issue by anusha94** [kubernetes-sigs/wg-policy-prototypes#117]
Some scale issues identified for `PolicyReport` can be found in this thread - https://github.com/open-policy-agent/gatekeeper/issues/2394

One option to tackle this issue is for the `PolicyReport` API to provide some kind of contract between `PolicyReport` generators and consumers. 
The proposal here is to add a `Configuration` field to the API -
```
configuration:
  limits:
    maxResults: 100
    statusFilter: ["FAIL", "WARN"]
```
This defines the max number of reports that will be stored. Also, provide a way to store only reports that the user may be interested in - the statusFilter allows to filter based on different status values - `pass, fail, error, warn, skip.`
The setting of these values should be exposed via the `PolicyReport` generator (for example, policy engines). The `PolicyReport` API should provide sane defaults for these fields

**Comment by anusha94** [comment]
@basit9958 Are you going to work on this issue?

**Comment by basit9958** [comment]
> @basit9958 Are you going to work on this issue?

I will push a pr by next week.
