### ISSUE TITLE
Add time fields

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes-sigs/wg-policy-prototypes#16]
Some choices:

- lastSeen
- firstSeen
- since 

Should these be at a result level?

**Comment by JimBugwadia** [comment]
Should the time fields be in each Result entry, the overall report, or both?

**Comment by RinkiyaKeDad** [comment]
Hi @JimBugwadia! I'd like to work on this. 

Could you please clarify what the Result entry and overall report refer to? I followed the [installing guide](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/README.md#installing) and got this output for the sample policy report resource:
![samplePR](https://user-images.githubusercontent.com/56963264/105978060-20794700-60b8-11eb-81b8-a827781d084a.png)

Is this is the overall report or a result entry?

**Comment by RinkiyaKeDad** [comment]
> Is this is the overall report or a result entry?

I realized this is a result entry. I think it will be good to have them in the overall report though the lastSeen could be added to each result entry. What do you think?

Also can you let me know how to view the overall report?
Thanks.

**Comment by phoenixking25** [comment]
@JimBugwadia if this is about the time taken you are referring to, then it should be at both level so one can see how much time each benchmark/test took and what was the aggregation that is overall level.
