### ISSUE TITLE
README should clearly document the expectations for this repo

### ISSUE THREAD

**Issue by enj** [kubernetes-sigs/wg-policy-prototypes#2]
Per https://github.com/kubernetes/org/issues/1669#issuecomment-607412211

Please add some warnings in the README to explicitly state that this is not supported code and should not be used in production environments.  Bonus points for fun emojis.

/cc @JimBugwadia

**Comment by JimBugwadia** [comment]
@enj - update PR: https://github.com/kubernetes-sigs/wg-policy-prototypes/pull/1. Let me know if any changes are required. Thanks!

**Comment by enj** [comment]
> @enj - updated PR: #1. Let me know if any changes are required. Thanks!

LGTM

**Comment by enj** [comment]
Fixed in #1
