### ISSUE TITLE
Protect Kubernetes community owned CRD

### ISSUE THREAD

**Issue by realshuting** [kubernetes-sigs/wg-policy-prototypes#25]
When deploying the current report definition to a cluster, Kubernetes warns that `MissingAnnotation`:
```
  - lastTransitionTime: "2020-11-11T02:28:40Z"
    message: protected groups must have approval annotation "api-approved.kubernetes.io",
      see https://github.com/kubernetes/enhancements/pull/1111
    reason: MissingAnnotation
    status: "False"
    type: KubernetesAPIApprovalPolicyConformant
```

Per https://github.com/kubernetes/enhancements/pull/1111, any CRD in group `k8s.io` should have annotation `api-approved.kubernetes.io` defined.

**Comment by JimBugwadia** [comment]
@realshuting - since with changed the group, can we close this issue?
