### ISSUE TITLE
Policy Violation CRD, controller, and adapters

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes-sigs/wg-policy-prototypes#3]
The Policy Violation CRD proposal aims to standardize how different Kubernetes policy management tools (OPA, Falco, Kyverno, kube-bench, etc.) can report non-conformance. The goal is to allow consistent reporting and management of policy violations.

There are three potential work areas for this proposal:

1. Define a Policy Violation CRD
2. Write a controller to manage policy violation life-cycles
3. Write adapters for select policy management projects to generate Policy Violation resources

**Comment by animeshk08** [comment]
Hi, @JimBugwadia, I am a junior year student of NITK Surathkal India.
Thank you so much for providing this project idea. I would be interested in working on this as a part of Community Bridge.

Can please let me know how to get started with this idea. 

Let me know if you prefer some other medium of communication(e.g slack, IRC, mail) with respect to this discussion.

**Comment by Dhiraj240** [comment]
@JimBugwadia  I have applied on community bridge and messaged you on slack for more information. You can check my portfolio here at https://dhiraj240.github.io/
