### ISSUE TITLE
CRD PolicyReport "source" property

### ISSUE THREAD

**Issue by fjogeleit** [kubernetes-sigs/wg-policy-prototypes#49]
Hey everyone,

I'm using the PolicyReport and ClusterPolicyReport implementation from Kyverno for my tool [Policy Reporter](https://github.com/fjogeleit/policy-reporter) which creates metrics and provides dashboards (standalone and Grafana based) für PolicyReportResults.

If more tools start to use this CRDs, I would like to be able to filter PolicyReports based on the tool who created the Report. This is not that easy if tools using different labels or annotations.

So, my feature Request is a new property "source" / "policyEngine" or similar to have the possibility to differentiate between the engines of reports.

**Comment by sunstonesecure-robert** [comment]
We did discuss this in the Jan 20 call ([noted in the google agenda doc](https://docs.google.com/document/d/1ihFfEfgViKlUMbY2NKxaJzBkgHh-Phk5hqKTzK-NEEs/edit?usp=sharing)  - however I don't recall what our decision was - annotation maybe?

I added this to the agenda for Wed - thanks for the reminder!! It was hypothetical before, but now it's a concrete need :)
