### ISSUE TITLE
Falco Policy Report CRD adapter

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes-sigs/wg-policy-prototypes#51]
Develop an adapter to convert Falco results and periodically generate or update a Policy Report custom resource based on the [WG Policy CRD](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/README.md).

The [Falco Sidekick](https://github.com/falcosecurity/falcosidekick) project may be the right integration point.

**Comment by sunstonesecure-robert** [comment]
I would lean towards a PR to Falco to produce policy reports rather than an adapter -  if we have native CRD generation in the tools themselves I think it benefits all "generators" and consumers.

but ... I fully recognize the practical ramp-up issues involved with that. ie having to understand falco code base vs just read in json and call custom resource api. maybe this project is a bridge to that longer term goal.

**Comment by JimBugwadia** [comment]
@sunstonesecure-robert - yes! The intent is to start with adapters and then revisit native support across tools.

**Comment by evalsocket** [comment]
@JimBugwadia I am familiar with falcosidekick codebase and WG policy CRD. Can this assign to me?

**Comment by JimBugwadia** [comment]
@evalsocket @sunstonesecure-robert - this work has been submitted as a LXF mentorship project and we will be selecting a mentee to work on it based on the timelines at:  https://github.com/cncf/mentoring/tree/master/lfx-mentorship/2021/02-Summer.

**Comment by rficcaglia** [comment]
Mea culpa! Jim can we post the previous and future proposals for projects
and internships in the repo somewhere for review?

**Comment by Aniket118** [comment]
Hello, @JimBugwadia I'm new to the CNCF community I'm interested in working on this project project idea. Can you please guide me on how to get started with it?

**Comment by JimBugwadia** [comment]
Hi @Aniket118 - thanks for your interest in contributing! 

This project has been submitted as a LXF mentorship project and we will be selecting a mentee to work on it based on the timelines at: https://github.com/cncf/mentoring/tree/master/lfx-mentorship/2021/02-Summer. Please feel free to apply there, and ask if you have any questions. Thanks!

**Comment by Aniket118** [comment]
Can you tell maximum of how many members can work on this project?

**Comment by JimBugwadia** [comment]
@Aniket118 - the project is for one mentee.

**Comment by Aniket118** [comment]
ok thanks

**Comment by JimBugwadia** [comment]
@anushkamittal20 - is this ready to be closed?

**Comment by anushkamittal20** [comment]
Hey @JimBugwadia, Thomas has to review and allow merge for this PR. I will reach out to him regarding this. I have done the work and changes he requested earlier.
