### ISSUE TITLE
Image Scanner -> Policy Report Adapter

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes-sigs/wg-policy-prototypes#54]
Develop an adapter to execute a periodic or event based image scan and convert results and to generate or update a Policy Report custom resource based on the [WG Policy CRD](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/README.md).

The tasks involved are:
1. Research available OSS image scanners like Clair and Trivy
2. Design how the scan should be run i.e. when a new image pull happens or periodically
3. Run the scan as a CronJob and produce the Policy Report CRD

**Comment by adeniyistephen** [comment]
Hi, I'm Stephen, I saw this project on the LFX projects and it needs a mentee for the project. I would love to work on this Image Scanner and also the Falco project, I was once a small Kubernetes contributor and terraform, I have not worked with Falco before or built a Policy report before, but I have worked with Go adapter on two different projects.

**Comment by JimBugwadia** [comment]
Hi @adeniyistephen - thanks for your interest and welcome to the working group! Please feel free to ask questions here or on our slack channel (https://kubernetes.slack.com/archives/C906A4GAF) to help you draft a proposal.

**Comment by adeniyistephen** [comment]
Alright, No problem sir @JimBugwadia . I will do just that.

**Comment by adeniyistephen** [comment]
@JimBugwadia Can't wait to start. :)

**Comment by JimBugwadia** [comment]
Closed via https://github.com/kubernetes-sigs/wg-policy-prototypes/pull/88.
