### ISSUE TITLE
Question: Should we be adopting API Review process for the CRD?

### ISSUE THREAD

**Issue by rficcaglia** [kubernetes-sigs/wg-policy-prototypes#55]
@neolit123 Thanks for opening eyes to this! 

https://github.com/kubernetes/community/blob/master/sig-architecture/api-review-process.md

I'm assuming they don't want to review CRDs per se, but should we ourselves follow the process? @JimBugwadia maybe you already did?

**Comment by neolit123** [comment]
https://github.com/kubernetes/community/blob/master/wg-policy/README.md
wg-policy seems to be sponsored by a lot of SIGs, so you could find a SIG member that also happens to be an API reviewer and ask them to do the voluntary CRD review:
https://github.com/kubernetes/community/blob/master/sig-architecture/api-review-process.md#voluntary

for example, a storage related CRD could be reviewed by one of these members:
https://github.com/kubernetes/kubernetes/blob/master/OWNERS_ALIASES#L511-L516

#api-reviews on k8s slack might have feedback too.

**Comment by JimBugwadia** [comment]
We have not done this, and it would be great to get a review!
