### ISSUE TITLE
KubeArmor support for producing PolicyReport CRs

### ISSUE THREAD

**Issue by rficcaglia** [kubernetes-sigs/wg-policy-prototypes#59]
Currently [KubeArmor](https://github.com/accuknox/KubeArmor) produces [bespoke Log output](https://github.com/accuknox/KubeArmor/blob/4ece0fe3768c868ea3bc0ea44678b425f8f42998/KubeArmor/types/types.go#L114).  

This feature request will add support for producing a [Policy Report](https://github.com/kubernetes-sigs/wg-policy-prototypes/tree/master/policy-report#policy-report) from KubeArmor. The implementation could be a native contribution to KubeArmor or an adapter that runs alongside KubeArmor and creates / updates the policy report.

**Comment by JimBugwadia** [comment]
@nyrahul - is this something best done natively in KubeArmor or as an adapter?

**Comment by nyrahul** [comment]
> @nyrahul - is this something best done natively in KubeArmor or as an adapter?

I believe this is best handled as an adapter since there are few users of kubearmor who might not want the policy report logs to be changed.

**Comment by rficcaglia** [comment]
maybe that is an opportunity for user community education? ie if we can
show the benefits of using a common report format vs. custom 1-off outputs
that need to be normalized for cross-component reporting there would be
less (or no) pushback

**Comment by jimil749** [comment]
Hello @JimBugwadia! Came across this via the CNCF mentorship repo. Would love to get involved. Any pointers to get started? :sweat_smile:

**Comment by JimBugwadia** [comment]
@jimil749 - thanks for your interest in contributing! You can take a look at the policy report CRD definition and KubeArmor's current output format as a start.
