### ISSUE TITLE
Kube Bench Adapter PolicyReport vs ClusterPolicyReport

### ISSUE THREAD

**Issue by fjogeleit** [kubernetes-sigs/wg-policy-prototypes#76]
Currently the Kube Bench Adapter creates a PolicyReport in the namespace of the CronJob.

My expectation from the work with kyverno would be a ClusterPolicyReport because the PolicyReportResults of the individual checks do not relate to resources in a namespace, but to the entire cluster.

**Comment by JimBugwadia** [comment]
@fjogeleit - agreed. The adapter should create multiple cluster policy reports, one for each target `node,policies,managedservices` etc.

**Comment by mritunjaysharma394** [comment]
Thanks, @fjogeleit and @JimBugwadia, I really loved this suggestion and will work on the improvements. 

/assign @mritunjaysharma394
