### ISSUE TITLE
Use wg-policy-prototypes as Go module to import generated code

### ISSUE THREAD

**Issue by danielpacak** [kubernetes-sigs/wg-policy-prototypes#79]
To implement an adapter out of tree or just use CRDs outside of this repo I'll have to generate client code from the API structs. This is probably something that multiple projects would do. Do you think that it makes sense to check in code generated by client-go generator and update it whenever there's a change in CRDs?

My use case is https://github.com/aquasecurity/starboard/issues/601 where we'd like to see if we can replace VulnerabilityReport CRD with PolicyReport, but I don't want to copy the skaffold for code-gen like [here](
https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/kube-bench-adapter/hack/update-codegen.sh) into our repo. Preferably I'd just import the wg-policy-prototypes repo as Go module and use generated clientset to access PolicyReport in a programmable way.

**Comment by JimBugwadia** [comment]
Hi @danielpacak - yes, that makes sense. Do you want to contribute a PR to move the generated directories to the common location from the kube-bench-adapter folder?

**Comment by danielpacak** [comment]
Sure, I can take it.
