### ISSUE TITLE
kube-bench adapter always runs the kube-bench job in the default namespace

### ISSUE THREAD

**Issue by patelrit** [kubernetes-sigs/wg-policy-prototypes#93]
kube-bench adapter always runs the kube-bench job in the default namespace even if the kube-bench adapter is deployed in a different namespace. It should be possible to specify the namespace where the kube-bench job is deployed and by default it should be deployed in the same namespace as the adapter (cron-job) since that is where the cluster role and cluster role bindings are created.

**Comment by mritunjaysharma394** [comment]
Thanks for the report! Will look into it and see how it can be fixed! 

/assign
