### ISSUE TITLE
kube-bench-adapter Job pending in Error State

### ISSUE THREAD

**Issue by fjogeleit** [kubernetes-sigs/wg-policy-prototypes#94]
On my local K3s Cluster the Jobs pending in Error state with the following logs:

```bash
Found (1) pods
pod (kube-bench-2zd4m) - "Pending"
Found (1) pods
pod (kube-bench-2zd4m) - "Succeeded"
failed to run job of kube-bench: invalid character 'A' looking for beginning of value
```

Kubernetes Version: v1.21.6+k3s1

**Comment by mirtov-alexey** [comment]
in my case the cronjob just hangs in the state:
` kubectl describe cronjob policyreport                                                                                                                                                               ─╯
Name:                          policyreport
Namespace:                     default
Labels:                        <none>
Annotations:                   <none>
Schedule:                      0 * * * *
Concurrency Policy:            Allow
Suspend:                       False
Successful Job History Limit:  3
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:           <none>
  Service Account:  clusterpolicyreport
  Containers:
   policyreport:
    Image:           mritunjay394/policyreport
    Port:            <none>
    Host Port:       <none>
    Environment:     <none>
    Mounts:          <none>
  Volumes:           <none>
Last Schedule Time:  <unset>
Active Jobs:         <none>
Events:              <none>`

and job is not created

at the same time, if I try to create just a pod with image image: mritunjay394/policyreport, then I also get an error `invalid character 'A' looking for beginning of value`

@mritunjaysharma394
