### ISSUE TITLE
Inconsistent field names

### ISSUE THREAD

**Issue by mattmoor** [kubernetes-sigs/wg-policy-prototypes#96]
I noticed in the documentation for v1alpha2 that the `json` field names and the names used in the comments are inconsistent here: https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/d747ba319734a9252c770654bc96af9071eb9d3d/policy-report/pkg/api/wgpolicyk8s.io/v1alpha2/policyreport_types.go#L96-L105

The Go fields and comments use `Subject`, but the `json` field uses `resource`

**Comment by anusha94** [comment]
The names changed when updating from `v1alpha1` to `v1alpha2`.

@JimBugwadia Is the json name same for compatibility reasons? In that case, we can change the Go field names. Else, change the json field names.

**Comment by JimBugwadia** [comment]
@anusha94 yes, lets change the Go field name and keep the JSON name the same for compatibility.
